### PR TITLE
FrozenLib But A Bit Better

### PR DESCRIPTION
**Pull request by AViewFromTheTop**

### CODE REVIEW

**Comment by Treetrain1** [comment]
@AViewFromTheTop could you look at my review

**Comment by AViewFromTheTop** [comment]
> @AViewFromTheTop could you look at my review

where's the review i dont see it

**Comment by AViewFromTheTop** [comment]
> like 3 comments above

i dont see it can you send a screenshot or smth

**Comment by Treetrain1** [comment]
image

**Comment by AViewFromTheTop** [comment]
the thing about the constructors is just to save space honestly, it's both cleaner and easier to manage with future updates that might change it

**Comment by AViewFromTheTop** [comment]
as for the merged rule... um
performance i guess
you can revert that if you want, but i'm honestly just worried about performance there

**Comment by AViewFromTheTop** [comment]
@Treetrain1 how about now

**Comment by Treetrain1** [comment]
wouldnt this result in memory leaks?

**Comment by Treetrain1** [comment]
> wouldnt this result in memory leaks?

wait no nvm the frozen surface rules are only made once

**Comment by Treetrain1** [comment]
> > wouldnt this result in memory leaks?
> 
> wait no nvm the frozen surface rules are only made once

wait no its made every time a mod calls the methods in `FrozenSurfaceRules`

**Comment by AViewFromTheTop** [comment]
@Treetrain1 check the newest commit
that might be how to make them update with each reload lmao

**Comment by AViewFromTheTop** [comment]
> wouldnt this result in memory leaks?

oh shit

**Comment by AViewFromTheTop** [comment]
well how tf would we fix the memory leak

**Comment by AViewFromTheTop** [comment]
> well how tf would we fix the memory leak

actually wait i have an idea

**Comment by AViewFromTheTop** [comment]
@Treetrain1 alright do you think my newest commit should fix it

**Comment by AViewFromTheTop** [comment]
it does

**Comment by AViewFromTheTop** [comment]
> bruh no monetization weight either bruhh (or idk that might be behind that toggle view revenue) image

ok what the fuck you were literally 50
honestly i mightve fucked it up so i take responsibility for it

**Comment by AViewFromTheTop** [comment]
there you go

**Comment by AViewFromTheTop** [comment]
can someone review this pr please

**Review by Treetrain1 — APPROVED** [review]
looks good
but i think merge should be delayed a bit to allow for us to transition to 1.20

**Comment by Treetrain1** [comment]
oh yeah quilt is out of beta now pog

**Review by Treetrain1 — CHANGES_REQUESTED** [review]
actually now that i think about it, could you update the changelog?

**Comment by AViewFromTheTop** [comment]
> actually now that i think about it, could you update the changelog?

ye

**Comment by AViewFromTheTop** [comment]
@Treetrain1 changelog done

**Review by Treetrain1 — APPROVED** [review]
now it looks good

**Comment by Treetrain1** [comment]
@AViewFromTheTop
Is this 100% ready for merge?

**Comment by AViewFromTheTop** [comment]
> @AViewFromTheTop Is this 100% ready for merge?

ye

**Comment by Treetrain1** [comment]
im gonna go ahead and merge this

**Pull request merged**
