### PR TITLE
Flyby sound improvements

### PR DESCRIPTION
**Pull request by AViewFromTheTop**

### CODE REVIEW

**Comment by Treetrain1** [comment]
If wonder if the player velocity is being used too strongly

**Comment by AViewFromTheTop** [comment]
> I wonder if the player velocity is being used too strongly

Not really-
We need to account for players moving *alongside* the other object (flybys shouldn’t really play then)
On top of that, they only play when moving vertically unless it’s going EXTREMELY fast, I have no clue what player velocity has to do with that

**Comment by AViewFromTheTop** [comment]
Thinking about it now, maybe we just have to divide the vertical velocity and use slightly more sensitive calculation and it would work
I’ll get in that once I have the time today unless you have ideas before me

**Comment by AViewFromTheTop** [comment]
Id prefer if you work on it now if you have the time because it’ll probably be like five or six hours for me until I can do anything

**Comment by AViewFromTheTop** [comment]
Honestly we need some sort of debug renderer for this that can show us each vector being used and how long it is
Unfortunately who the hell knows how to do that..???!!!?!?!

**Comment by AViewFromTheTop** [comment]
Maybe Ludo?

**Comment by Treetrain1** [comment]
> Id prefer if you work on it now if you have the time because it’ll probably be like five or six hours for me until I can do anything

man i just got online ☠️

**Comment by Treetrain1** [comment]
> Honestly we need some sort of debug renderer for this that can show us each vector being used and how long it is Unfortunately who the hell knows how to do that..???!!!?!?!

mojang
we get mojang to help us /j

**Comment by AViewFromTheTop** [comment]
> man i just got online ☠️

Wdym online

**Comment by AViewFromTheTop** [comment]
Also I have to take a shower rn

**Comment by AViewFromTheTop** [comment]
@Treetrain1 im so confused

**Comment by AViewFromTheTop** [comment]
@Treetrain1 @MerpisMe FLYBYS ARE WORKINGGGGGG

**Comment by MerpisMe** [comment]
can they clean my glasses

**Comment by AViewFromTheTop** [comment]
> can they clean my glasses

huh-
whats the connection im confused

**Comment by MerpisMe** [comment]
> > can they clean my glasses
> 
> huh- whats the connection im confused

nothing i'm just wondering if they can
my glasses are pretty dirty rn

**Comment by AViewFromTheTop** [comment]
did you try microwaving them

**Comment by MerpisMe** [comment]
yea
listen if flybys can't clean my glasses then I DONT CARE ABOUT THEM‼️‼️‼️‼️‼️ /j
(congrats on fixing them!!!)

**Comment by AViewFromTheTop** [comment]
> yea listen if flybys can't clean my glasses then I DONT CARE ABOUT THEM‼️‼️‼️‼️‼️

fuck youuuuu

> /j

/jellyfish

> (congrats on fixing them!!!)

why

**Comment by MerpisMe** [comment]
54321

**Comment by AViewFromTheTop** [comment]
> 54321

gay communication at its finest

**Comment by AViewFromTheTop** [comment]
what the fuck does 54321 mean

**Comment by MerpisMe** [comment]
it's the amount of time you have left until the ballistic missiles i sent to your house land

run

**Comment by AViewFromTheTop** [comment]
> it's the amount of time you have left until the ballistic missiles i sent to your house land
> 
> run

well i hope thats soon

**Comment by MerpisMe** [comment]
54321 years

**Comment by AViewFromTheTop** [comment]
> 54321 years

god damnit

**Review by Treetrain1 — APPROVED** [review]
Love the changes
glad they actually work now

this ready to merge?

**Comment by AViewFromTheTop** [comment]
> Love the changes glad they actually work now
> 
> this ready to merge?

Id like if you could see if there’s anything you can tweak, but if you can’t come up with anything just go ahead and merge

**Comment by Treetrain1** [comment]
> > Love the changes glad they actually work now
> > this ready to merge?
> 
> Id like if you could see if there’s anything you can tweak, but if you can’t come up with anything just go ahead and merge

honestly ive had it work almost flawlessly
dont know if theres much to tweak at the moment
im just going to go ahead and merge

**Comment by AViewFromTheTop** [comment]
> honestly ive had it work almost flawlessly dont know if theres much to tweak at the moment im just going to go ahead and merge

oh LMAO it didn’t think my new implementation would be considered “almost flawless” thank you sidjdkdk 
to be honest I think it has quite a few flaws that I can’t exactly fix, but luckily they’re small flaws anyway
Anyway, it’s infinitely better than the bullshit I made before lmfao

**Pull request merged**
