### PR TITLE
better sound

### PR DESCRIPTION
**Pull request by AViewFromTheTop**

### CODE REVIEW

**Review by Treetrain1 — APPROVED** [review]

**Comment by Treetrain1** [comment]
everything here good to merge?

**Comment by AViewFromTheTop** [comment]
> everything here good to merge?

I want to wait a bit longer to be safe in case I add anything
I’m feeling a little better today so there’s a small chance I’ll tinker with stuff

**Comment by AViewFromTheTop** [comment]
@Treetrain1 the latest commit on here is absolutely critical for frozenlib, just a heads up
go ahead and merge if youd like lol

**Comment by AViewFromTheTop** [comment]
without that commit it would take forever and have fabric api included in the final build (which i believe the owner of fapi caused a TON of drama about, hence why nobody is allowed to do it anymore) *and* it would cause a crash upon loading

**Comment by Treetrain1** [comment]
for now i just disabled lithium's nbtcompound mixin as a temporary fix
hopefully at some point a better fix can be made

**Comment by AViewFromTheTop** [comment]
@Treetrain1 keep in mind that the client needs to be able to *read* the byte buf lol
maybe having each module named?

**Comment by AViewFromTheTop** [comment]
@Treetrain1 can the wind extensions save their own nbt? i didnt see that in the wilder wind thing
just want to make sure since thats important

**Comment by AViewFromTheTop** [comment]
once that's taken care of, honestly i think 2.1 is gonna be pretty much complete
idk what else to change at the moment, unless soro has any ideas

**Comment by Treetrain1** [comment]
> @Treetrain1 can the wind extensions save their own nbt? i didnt see that in the wilder wind thing just want to make sure since thats important

yes

image

**Comment by AViewFromTheTop** [comment]
> > @Treetrain1 can the wind extensions save their own nbt? i didnt see that in the wilder wind thing just want to make sure since thats important
> 
> yes
> 
> image

Oh
pogggggg
I’m gonna go to bed now
Just know your work today was amazing

**Comment by AViewFromTheTop** [comment]
Also what’s safeString

**Comment by Treetrain1** [comment]
> Also what’s safeString

like a resourcelocation but the `:` is replaced with an `_`
to support nbt

**Pull request merged**
